name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race ./...

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mcp-memory-core:latest
